task: add artifacts
DARPA-ASKEM/.github pull request #8
Opened 2023-09-13 18:30 UTC by YohannParis

* Added a an extra steps to downloads all artifacts defined in previous jobs.
* Set an ENV named `ARTIFACT` to be used by `docker-bake.hcl` to use.

2023-09-13 19:02 UTC, Nithos commented on .github/workflows/bake-publish.yaml
> +          echo "ARTIFACT=${{ ARTIFACT_PATH }}${{ inputs.artifact }}" >> ${GITHUB_ENV}
do we need a `/` between the ENV and the inputs value?

2023-09-13 19:02 UTC, Nithos commented on .github/workflows/bake-publish.yaml
> +          echo "ARTIFACT=${{ ARTIFACT_PATH }}${{ inputs.artifact }}" >> ${GITHUB_ENV}
whats your use within the bake file? is this just meant to be used in the 
```
dockerfile: ${ARTIFCT}
```

2023-09-14 13:07 UTC, YohannParis commented on .github/workflows/bake-publish.yaml
> +          echo "ARTIFACT=${{ ARTIFACT_PATH }}${{ inputs.artifact }}" >> ${GITHUB_ENV}
Yes, it's for the bake file to have a path a file as needed, or a folder if someone wants:
```hcl
target "skema-text-reading-base" {
  context = "."
  tags = tag("skema-text-reading", "", "")
  dockerfile = "${ARTIFACT}"
}
```

2023-09-14 13:26 UTC, Nithos commented on .github/workflows/bake-publish.yaml
> +          echo "ARTIFACT=${{ ARTIFACT_PATH }}${{ inputs.artifact }}" >> ${GITHUB_ENV}
Ok, so I would try linking to this branch directly in your skema repo and testing this next to see if it works before committing

2023-09-14 15:51 UTC, Nithos approved these changes

2023-09-14 15:52 UTC, Nithos requested changes
Need to modify the other publish file as well or remove it

2023-09-14 15:53 UTC, Nithos commented on .github/workflows/bake-publish.yaml
>          with:
please remove this as well, or make a separate PR for this, it should no longer be needed.
It was pinned to a version due to an upgrade that was done earlier this year that caused issues, I believe this has been resolved now as I am not using it in any other version except in ASKEM

2023-09-14 15:54 UTC, Nithos commented on .github/workflows/bake-publish.yaml
>          with:
comment seems off...
I mean the `with:` section that sets the driver version

2023-09-14 17:45 UTC, Nithos approved these changes

2023-09-14 17:46 UTC, Nithos commented on .github/workflows/bake-publish.yaml
>          with:
Can be done as a separate PR. Feel free to resolve this and merge.

2024-03-15 15:35 UTC, merged